# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15B3qnyCP2UtuqjiodcCjy-GAy4I6vkUn
"""

TASK 1
product_num = eval(input("Enter Number of products: "))
dict ={}
for x in range(product_num):
    productName = input("Enter Product Name: ")
    productPrice = int(input("Enter Product Price"))
    my_dict[productName] = productPrice


while True:
    productName = input("Enter Product name to get Price")
    if productName in dict:
        print("The price for your product is ", dict[productName])

    else:
        print("This product is not found in dictionary")


print(dict)

TASK2:

  
dict ={'Mansiom': '10000','Car':'2000','Laptop':'500'}
print(dict)

amount =eval(input("Enter Amount: $$"))
for key ,values in dict.items():
    if  int(values) < amount:
        print (key ,"->",values

TASK 3:
year ={"January":"31","Febuary":"28","March":"30","April":"30","May":"31","June":"30"}

Part a
user_input= input("Enter Name of a month: ")
for key, values in year.items():
     if user_input == key:  
        print( values)
		
Part b
sorted_year ={key:year[key] for key in sorted(year)}
print(sorted_year.keys())

Part c
for keys,values in year.items():
    if int(values) == 31:
      print(keys)

Part d
sorted_bymonthdays = dict(sorted(year.items(),key= operator.itemgetter(1)))
print(sorted_bymonthdays)

TASK 4:
for keys ,values in user_dict.items():
        if keys == x  and y == user_dict[keys]:
            return ("you are logged in",keys,user_dict[keys])
        else:
            return  ("Invalid.")
x = input("Enter Username: ")    
y = input("Enter Your Password ")
print(User_Password(x,y))

TASK 5:
    numberofTeams = int(input("Enter Number of Teams: "))
    team_dict={}
    score_list =[]
    winning_record =[]
    percentage_score = 0
    for team in range(numberofTeams):
        team_name = input("Enter Team Name: ")
        team_winning_score = int(input("Team Winning game: "))
        team_dict.update({team_name:team_winning_score})
        score_list.append(team_winning_score)
        winning_record.append(team_name)

    userinput = input("Enter team to check % of wins: ")
    for  keys,values in team_dict.items():

         if userinput == keys:
            score = team_dict[keys]
            percentage_score = (score/100)* 100

    return "Your teams list is {},Percentage win of team {}%, All team with winning record  {}".format(team_dict,percentage_score,winning_record)

TASK 6:
num_team =int(input("Enter Number Of Teams: "))
   team_dict={}
   for team in range(num_team):
       key = input("Enter Team name: ")
       value =[]
       wins = int(input("Enter Win: "))
       losses = int(input("Enter Losses: "))
       value.extend((wins,losses))
       team_dict.update({key:value})
       
   return team_dict

print(teamInfo())

TASK 7:
matrix_5= [1,2,3,4,5,
           5,6,7,4,5,
           6,7,8,0,3,
           4,2,1,5,6,
           7,8,9,0,5]

def creatList():
    matrix_dict={}
    for num in range(len(matrix_5)):
        key = matrix_5[num]
        value = matrix_5.count(key)
        matrix_dict.update({key:value})
    return matrix_dict



print(creatList())

TASK 8:
all_card ={"One":1,"Two":2,"Three":3,"Four":4,"Five":5,"Six":6,"Seven":7,"Eight":8,"Nine":9,"Ten":10}
cards = 3
player1Card =[]
player2Card =[]
for card in range(cards):
    c1 =random.choice(list(all_card.values()))
    c2= random.choice(list(all_card.values()))
    player1Card.append(c1)
    player2Card.append(c2)

if sum(player1Card) > sum(player2Card):
    print("Player 1 wins with ",sum(player1Card)," Against Player 2 with",sum(player2Card))
elif sum(player2Card) > sum(player1Card):
    print("Player 2 wins with ",sum(player2Card)," Against Player 1 with",sum(player1Card))

TASK 14:
d=[{'name':'Talha', 'phone':'033-1784', 'email':'talha@mail.net'},
{'name':'Humna', 'phone':'5321-1948', 'email':'humna@mail.com'},
{'name':'maryam', 'phone':'925-3091', 'email':'maryam@gmail.com'},
{'name':'ali', 'phone':'165-0518', 'email':'ali@gmail.COM'}
for dict  in  range(len(d)):
     dd =d[dict ]
     for keys,values in dd.items():
         if keys == "phone" and values[-1] == "8":
             print(dd)
         if keys == "email" and values =='':
            print(dd)